networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_password:
    file: ../secrets/wp_password.txt

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jteissie/data/wordpress'
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jteissie/data/mariadb'

services:
  nginx:
    container_name: nginx
    build: 
      context: requirements/nginx/.
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      wordpress:
        condition: service_healthy
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb/.
      dockerfile: Dockerfile
    healthcheck:
      test: mysqladmin ping
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    env_file: .env
    restart: unless-stopped
    secrets:
      - db_password
    expose:
      - "3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: 
      context: requirements/wordpress/.
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: netstat -an | grep 9000 > /dev/null || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    env_file: .env
    restart: unless-stopped
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    secrets:
      - db_password
      - db_root_password
      - wp_password

  redis:
    container_name: redis
    build:
      context: requirements/bonus/redis-cache/.
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - inception
    expose:
      - "6379"

  adminer:
    container_name: adminer
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    init: true
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER}
      - ADMINER_USERNAME=${ADMINER_USERNAME}
      - ADMINER_PASSWORD=${ADMINER_PASSWORD}
    networks:
      - inception
    pull_policy: never
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped
    expose:
      - "7000"
 
  ftp:
    container_name: ftp-server
    build:
      context: requirements/bonus/ftp/.
      dockerfile: Dockerfile
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    init: true
    env_file: .env
    restart: unless-stopped
    pull_policy: never
    depends_on:
      wordpress:
        condition: service_healthy
    networks: 
      - inception
    ports:
      - "20-21:20-21"
      - "30000-30010:30000-30010"        
    volumes:
      - wordpress:/var/www/html

  elastic:
    container_name: elasticsearch
    build:
      context: requirements/bonus/elastic/.
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    pull_policy: never
    depends_on:
      wordpress:
        condition: service_healthy
    networks: inception
    ports:
      - "9200"
      - "9300"

